### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by MartinRep** [grei-ufc/pade#10]
Hello,
I am trying to start using your project but I keep getting this error when I try to run one of your examples. I followed your tutorial video, but getting the same error. It seems there's a problem with one of the library files as the path is missing the "\\". Here's the Traceback: 

Traceback (most recent call last):
  File "C:\Users\MartinRep\.conda\envs\pade\Scripts\pade-script.py", line 11, in <module>
    load_entry_point('pade==2.1.2', 'console_scripts', 'pade')()
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\pade-2.1.2-py3.7.egg\pade\cli\pade_cmd.py", line 215, in start_runtime
    main(config)
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\pade-2.1.2-py3.7.egg\pade\cli\pade_cmd.py", line 134, in main
    from pade.core import sniffer
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\pade-2.1.2-py3.7.egg\pade\core\sniffer.py", line 25, in <module>
    MESSAGES = Table('messages', METADATA, autoload=True, autoload_with=ENGINE)
  File "<string>", line 2, in __new__
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\sqlalchemy-1.3.4-py3.7-win-amd64.egg\sqlalchemy\util\deprecations.py", line 130, in warned
    return fn(*args, **kwargs)
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\sqlalchemy-1.3.4-py3.7-win-amd64.egg\sqlalchemy\sql\schema.py", line 496, in __new__
    metadata._remove_table(name, schema)
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\sqlalchemy-1.3.4-py3.7-win-amd64.egg\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\sqlalchemy-1.3.4-py3.7-win-amd64.egg\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\sqlalchemy-1.3.4-py3.7-win-amd64.egg\sqlalchemy\sql\schema.py", line 491, in __new__
    table._init(name, metadata, *args, **kw)
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\sqlalchemy-1.3.4-py3.7-win-amd64.egg\sqlalchemy\sql\schema.py", line 585, in _init
    resolve_fks=resolve_fks,
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\sqlalchemy-1.3.4-py3.7-win-amd64.egg\sqlalchemy\sql\schema.py", line 609, in _autoload
    _extend_on=_extend_on,
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\sqlalchemy-1.3.4-py3.7-win-amd64.egg\sqlalchemy\engine\base.py", line 2147, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\sqlalchemy-1.3.4-py3.7-win-amd64.egg\sqlalchemy\engine\base.py", line 1604, in run_callable
python: can't open file **'C:UsersMartinRep.condaenvspadelibsite-packagespade-2.1.2-py3.7.eggpadecorenew_ams.py': [Errno 2] No such file or directory**
    return callable_(self, *args, **kwargs)
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\sqlalchemy-1.3.4-py3.7-win-amd64.egg\sqlalchemy\engine\default.py", line 429, in reflecttable
    table, include_columns, exclude_columns, resolve_fks, **opts
  File "C:\Users\MartinRep\.conda\envs\pade\lib\site-packages\sqlalchemy-1.3.4-py3.7-win-amd64.egg\sqlalchemy\engine\reflection.py", line 646, in reflecttable
    raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: messages

**Comment by lucassm** [comment]
Hello @MartinRep , sorry for this late answer, but you can try this comand:
`pade create-pade-db`
This is necessary because in the first time whe you try to run PADE there is no database tables, then you need to create it with this command. This will happened every time that you restart your machine, because the DB is created in the system temporary folder. 
If you have more trouble with PADE you can send questions and I will respond in a more quickly way ;)

**Comment by JPetriNet** [comment]
Hello,

I have the same error. Creating the pade db with the command "pade create-pade-db" ran successfully. However, I still get the error. Any advice? 

Thanks in advance!
