### ISSUE TITLE
when running agent_example1

### ISSUE THREAD

**Issue by HGcore2** [grei-ufc/pade#32]
Process FlaskServerProcess-1:
Traceback (most recent call last):
  File "c:\users\h\appdata\local\programs\python\python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\pade\cli\pade_cmd.py", line 51, in run
    run_server(self.secure)
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\pade\web\flask_server.py", line 584, in run_server
    login_manager._login_disabled = True
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\flask_login\login_manager.py", line 467, in _login_disabled
    current_app.config['LOGIN_DISABLED'] = newvalue
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "c:\users\h\appdata\local\programs\python\python37\lib\site-packages\flask\globals.py", line 52, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.

**Comment by lucassm** [comment]
Hello @HGcore2 ! I think that was an issue in PADE source code that was already resolved. Download the most recent version of PADE, install it, and test to ensure that this problem will not occur again.
