### ISSUE TITLE
Script `pade` tenta utilizar diretório sem acesso de escrita para salvar banco de dados

### ISSUE THREAD

**Issue by filipesaraiva** [grei-ufc/pade#6]
Estamos testando um simples enviar-receber mensagens com o PADE mas estamos pegando a seguinte mensagem de erro:

```python
Traceback (most recent call last):
  File "exchanges-messages.py", line 84, in <module>
    start_loop(agentes)
  File "/usr/lib/python3.7/site-packages/pade/misc/utility.py", line 55, in start_loop
    ILP = reactor.listenTCP(agent.aid.port, agent.agentInstance)
  File "/usr/lib/python3.7/site-packages/Twisted-18.9.0-py3.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/usr/lib/python3.7/site-packages/Twisted-18.9.0-py3.7-linux-x86_64.egg/twisted/internet/tcp.py", line 1363, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:8000: [Errno 98] Address already in use.
```
Não sei se o problema está em nossa implementação. Se possível, poderia nos ajudar a apontar o que pode estar errado no código em anexo? Obrigado.

[exchanges-messages.txt](https://github.com/grei-ufc/pade/files/2937506/exchanges-messages.txt)

**Comment by filipesaraiva** [comment]
cc @kellydosocorro

**Comment by lucassm** [comment]
Filipe e Kelly,

O erro que está ocorrendo informa que a porta 8000 já está em uso e que portanto não pode ser utilizada por outro processo. Essa porta normalmente é utilizada pelo agente AMS do Pade.

Às vezes, o AMS pode ficar executando mesmo após o encerramento quando o Pade é encerrado bruscamente por algum tipo de erro.

Para ter certeza que existe algum processo rodando nessa porta, no terminal do linux, você pode executar o comando `nmap localhost`. Para matar esse processo, execute: `fuser -k 8000/tcp`.

Se não der certo pode me contactar para marcarmos uma vídeo rápida, ok?

**Comment by filipesaraiva** [comment]
Oi @lucasssm, obrigado. Minha dúvida é porque não há realmente nada rodando naquela porta. Será que temos algo errado na implementação, no arquivo anexo no primeiro comentário?

Vou te enviar a mensagem de erro completa abaixo. Há várias exceções, talvez seja algum erro com elas... estou utilizando o PADE instalado via pip.

```python
$ pade exchanges-messages.py 
please enter a username [pade_user]: 
Password [12345]: 

        This is
         ____   _    ____  _____ 
        |  _ \ / \  |  _ \| ____|
        | |_) / _ \ | | | |  _|  
        |  __/ ___ \| |_| | |___ 
        |_| /_/   \_\____/|_____|
        
        Python Agent DEvelopment framework   
        

        PADE is a free software under development by
        Electric Smart Grid Group - GREI
        Federal University of Ceara - UFC - Brazil

        https://github.com/grei-ufc/pade
 * Serving Flask app "pade.web.flask_server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 546, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pade/core/new_ams.py", line 332, in <module>
    ams._initialize_database()
  File "/usr/lib/python3.7/site-packages/pade/core/new_ams.py", line 294, in _initialize_database
    db.drop_all()
  File "/usr/lib/python3.7/site-packages/Flask_SQLAlchemy-2.3.2-py3.7.egg/flask_sqlalchemy/__init__.py", line 971, in drop_all
    self._execute_for_all_tables(app, bind, 'drop_all')
  File "/usr/lib/python3.7/site-packages/Flask_SQLAlchemy-2.3.2-py3.7.egg/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/sql/schema.py", line 4256, in drop_all
    ddl.SchemaDropper, self, checkfirst=checkfirst, tables=tables
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2033, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 949, in visit_metadata
    table, drop_ok=True, _is_metadata_operation=True
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 1002, in visit_table
    self.connection.execute(DropTable(table))
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/util/compat.py", line 374, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.0b2-py3.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 546, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: '\nDROP TABLE messages'] (Background on this error at: http://sqlalche.me/e/e3q8)
[sniffer@localhost:8001] 06/03/2019 15:56:55 --> Connection Failed...
[Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 111: Connection refused.
]
[destinatario] 06/03/2019 15:56:58 --> Destinatario construído
[remetente] 06/03/2019 15:56:58 --> Remetente construído
[remetente] 06/03/2019 15:56:58 --> Enviando Mensagem
[remetente] 06/03/2019 15:56:58 --> <?xml version="1.0" ?>
<ACLMessage>
        <performative>inform</performative>
        <system-message/>
        <sender/>
        <receivers>
                <receiver>destinatario@localhost:51600</receiver>
        </receivers>
        <reply-to/>
        <content>Ola, eu estou aqui</content>
        <language/>
        <enconding/>
        <ontology/>
        <protocol>fipa-request protocol</protocol>
        <conversationID>9e670060-4041-11e9-a01f-7cb0c200a663</conversationID>
        <messageID>9e6701be-4041-11e9-a01f-7cb0c200a663</messageID>
        <reply-with/>
        <in-reply-to/>
        <reply-by/>
        <reply-by/>
        <datetime>
                <day>6</day>
                <month>3</month>
                <year>2019</year>
                <hour>15</hour>
                <minute>56</minute>
                <second>58</second>
                <microsecond>611363</microsecond>
        </datetime>
</ACLMessage>

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/Twisted-18.9.0-py3.7-linux-x86_64.egg/twisted/internet/tcp.py", line 1361, in startListening
    skt.bind(addr)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exchanges-messages.py", line 84, in <module>
    start_loop(agentes)
  File "/usr/lib/python3.7/site-packages/pade/misc/utility.py", line 55, in start_loop
    ILP = reactor.listenTCP(agent.aid.port, agent.agentInstance)
  File "/usr/lib/python3.7/site-packages/Twisted-18.9.0-py3.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/usr/lib/python3.7/site-packages/Twisted-18.9.0-py3.7-linux-x86_64.egg/twisted/internet/tcp.py", line 1363, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:8000: [Errno 98] Address already in use.
```

**Comment by lucassm** [comment]
@filipesaraiva parece que o primeiro erro que ocorreu foi uma falha no acesso ao banco de dados. Acho que eu sei o que aconteceu. Como o banco de dados do sqlite é apenas um arquivo e você não está utilizando um ambiente virtual, houve um erro quando o Pade tentou inserir um registro neste banco, pois ele está em uma pasta restrita `/usr/lib/python3.7/site-packages/pade/`.
Tente instalar o Pade em um ambiente virtual e veja o que acontece.
Eu aconselho a utilização do [anaconda](https://www.anaconda.com/distribution/) para criar o ambiente virtual.
