### ISSUE TITLE
Help in start and using pade

### ISSUE THREAD

**Issue by euclidesfjr** [grei-ufc/pade#8]
Hello, I am new to using pade, however I tried to use the installation documentation and tests, but the system does not run properly, because in the documentation asks me to perform the following:
euclidesfjr @ kaxassa: ~ $ pade
Usage: pade [OPTIONS] COMMAND [ARGS] ...

Options:
  --help Show this message and exit.

Commands:
  create-pade-db
  drop-pade-db
  start-runtime
  start-web-interface
__________________________

But all the commands are with "_" and not "-", another thing the system hangs and does not show more information, how can I solve it? Another problem is that the system asks for a username and password, but I do not have the information how to create the user or which user is to be used in the system. The error below also reports SQL problem, which I have no info on how to fix. Look at the following problem:

euclidesfjr@kaxassa:~/pade/examples$ pade start_ams.py
please enter a username [pade_user]: euclidesfjr
Password [12345]: 
        This is
         ____   _    ____  _____ 
        |  _ \ / \  |  _ \| ____|
        | |_) / _ \ | | | |  _|  
        |  __/ ___ \| |_| | |___ 
        |_| /_/   \_\____/|_____|
        
        Python Agent DEvelopment framework   
        

        PADE is a free software under development by
        Electric Smart Grid Group - GREI
        Federal University of Ceara - UFC - Brazil

        https://github.com/grei-ufc/pade
 * Serving Flask app "pade.web.flask_server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pade/core/new_ams.py", line 332, in <module>
    ams._initialize_database()
  File "/usr/local/lib/python3.5/dist-packages/pade/core/new_ams.py", line 294, in _initialize_database
    db.drop_all()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 971, in drop_all
    self._execute_for_all_tables(app, bind, 'drop_all')
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 4313, in drop_all
    ddl.SchemaDropper, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2033, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 949, in visit_metadata
    table, drop_ok=True, _is_metadata_operation=True
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 1002, in visit_table
    self.connection.execute(DropTable(table))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: 
DROP TABLE messages]
(Background on this error at: http://sqlalche.me/e/e3q8)
 * Serving Flask app "pade.web.flask_server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "start_ams.py", line 21, in <module>
    s.start_loop()
  File "/usr/local/lib/python2.7/dist-packages/pade-2.1.2-py2.7.egg/pade/misc/common.py", line 207, in start_loop
    self._initialize_database()
  File "/usr/local/lib/python2.7/dist-packages/pade-2.1.2-py2.7.egg/pade/misc/common.py", line 144, in _initialize_database
    db.drop_all()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 971, in drop_all
    self._execute_for_all_tables(app, bind, 'drop_all')
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 4313, in drop_all
    ddl.SchemaDropper, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2033, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 949, in visit_metadata
    table, drop_ok=True, _is_metadata_operation=True
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
Process FlaskServerProcess-1:
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 1002, in visit_table
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.connection.execute(DropTable(table))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: 
DROP TABLE messages]

**Comment by lucassm** [comment]
Hello @euclidesfjr !
Sorry for delay in responding your question, but I was working in correct a PADE DB behaviour, and I think that now you can run PADE in your machine, without the errors that happened before.
But, first I have some tips to improve your experience with PADE:
- First of all I recommend that you use Python with Anaconda3 virtual environments, its free and you can get it in this link: https://www.anaconda.com/distribution/
- I have seen too that you are using Python 2.7, but PADE it will only works with Python 3.7 (Anaconda will solve this problem for you).
-  And finally, I had recorded a video with the PADE installation process, and you can watch it through this link: https://asciinema.org/a/ELHfOxZnMUjZyLa8bITJ0AQnP. I think it will be useful for you.

Thanks for your questions and if have more, don't hesitate in made yours questions through this channel.

**Comment by franlu** [comment]
Hello! 

> Commands:
>   create-pade-db
>   drop-pade-db
>   start-runtime
>   start-web-interface
> 
> But all the commands are with "_" and not "-"

I have had the same problem with the commands :joy: I spend some time searching the problem. 
It's not a priority, but it helps to use it.

I also take time searching the email and password to login web interface. I find it by code.

I will send a pull request with small changes in readme file.

Bye!
